# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Julia Belyakova
tagline:          'Northeastern University'
description:      'PhD Student at 
<a href="https://www.khoury.northeastern.edu/">Khoury</a>, <a href="https://www.northeastern.edu/">NEU</a> (Boston, MA)'

url:              https://julbinb.github.io
files:            files
papers:           files/papers
slides:           files/slides
projects:         projects
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Julia Belyakova'
  url:            julbinb.github.io/

#paginate:         5
#paginate_path:    '/blog/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.6.0
sidebar_home_link:  true
#sidebar_blog_link:  '/blog'

github:
  account:          https://github.com/julbinb/
  repo:             https://github.com/julbinb/julbinb.github.io
twitter:            https://twitter.com/julbinb
facebook:           https://www.facebook.com/julbinb
researchgate:       https://www.researchgate.net/profile/Julia_Belyakova
linkedin:           https://www.linkedin.com/in/julbinb/

# Links to webpages
people:
  artem:            https://a-pelenitsyn.github.io/
  vitaly:           https://bravit.guru/
  ssm:              https://sfedu.ru/person/miks
  jan:              http://janvitek.org/
  bengreenman:      http://ccs.neu.edu/home/types/

# Contact-me text
contactmetext: 'please, feel free to <a href="mailto:julbinb@gmail.com">email me</a>
  or submit your feedback
  <a target="_blank" href="https://forms.gle/aS9Y9pHSiMGhRPm67">using this Google form</a>.
  I would be happy to answer questions that you might have,
  learn about what is unclear or confusing, or receive any other feedback.'
